import type {
  Product,
  Order,
  LicenseKey,
  Coupon,
  Webhook,
  TeamMember,
  ActivityLog,
  DashboardStats,
  ChartData,
  Notification,
} from './admin-types';

// Helper to generate dates
const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000);
const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000);

// Mock Products - All 16 games
export const mockProducts: Product[] = [
  {
    id: 'prod_1',
    name: 'Armani',
    slug: 'armani-apex',
    description: 'Premium Apex Legends cheat with advanced aimbot and ESP features. Dominate every match with our undetected software.',
    image: '/images/apex-product.png',
    gallery: ['/images/apex-product.png'],
    game: 'Apex Legends',
    status: 'active',
    features: {
      aimbot: ['Aimbot enable', 'Aim key', 'Aim on shoot', 'Visibility check', 'Field of view', 'Bone selector', 'Target switch delay', 'Nearest coefficient', 'Aimbot speed'],
      esp: ['Enemy box ESP', 'Enemy line', 'Enemy distance ESP', 'Enemy health ESP', 'Enemy shield ESP', 'Enemy name', 'Player team check', 'Skeleton ESP', 'Item ESP', 'Item filters', 'Loot ESP', 'Night mode', 'Knocked out text'],
      misc: ['Skin changer', 'Custom crosshair', 'Distance unit selection'],
    },
    pricing: [
      { duration: '1 Day', price: 7.90, stock: 15 },
      { duration: '7 Days', price: 39.90, stock: 8 },
      { duration: '30 Days', price: 69.90, stock: 3 },
    ],
    requirements: {
      cpu: 'Intel only',
      windows: '10 - 11',
      cheatType: 'External',
      controller: true,
    },
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
  },
  {
    id: 'prod_2',
    name: 'HWID Spoofer',
    slug: 'hwid-spoofer',
    description: 'Advanced HWID Spoofer to bypass hardware bans. Works with all major anti-cheat systems including EAC, BattlEye, and Vanguard.',
    image: '/images/hwid-spoofer.jpg',
    gallery: ['/images/hwid-spoofer.jpg'],
    game: 'Universal',
    status: 'active',
    features: {
      aimbot: [],
      esp: [],
      misc: ['Disk spoof', 'MAC spoof', 'Motherboard spoof', 'GPU spoof', 'Monitor spoof', 'USB spoof', 'RAM spoof', 'Registry cleaner', 'Trace remover', 'Auto-update'],
    },
    pricing: [
      { duration: '1 Day', price: 4.90, stock: 50 },
      { duration: '7 Days', price: 14.90, stock: 30 },
      { duration: '30 Days', price: 29.90, stock: 20 },
      { duration: 'Lifetime', price: 79.90, stock: 10 },
    ],
    requirements: {
      cpu: 'Intel & AMD',
      windows: '10 - 11',
      cheatType: 'External',
      controller: false,
    },
    createdAt: daysAgo(120),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_3',
    name: 'Fortnite',
    slug: 'fortnite',
    description: 'Dominate Fortnite with our premium cheat. Features advanced aimbot with prediction, full ESP, and exclusive features.',
    image: '/images/fortnite.jpg',
    gallery: ['/images/fortnite.jpg'],
    game: 'Fortnite',
    status: 'active',
    features: {
      aimbot: ['Aimbot enable', 'Aim key', 'Silent aim', 'Bullet prediction', 'FOV circle', 'Smoothing', 'Target priority', 'Auto fire'],
      esp: ['Player ESP', 'Box ESP', 'Skeleton', 'Health bars', 'Distance', 'Weapon ESP', 'Vehicle ESP', 'Chest ESP', 'Loot ESP', 'Supply drop ESP'],
      misc: ['No recoil', 'No spread', 'Instant edit', 'Build assist', 'Custom crosshair'],
    },
    pricing: [
      { duration: '1 Day', price: 8.90, stock: 20 },
      { duration: '7 Days', price: 44.90, stock: 15 },
      { duration: '30 Days', price: 79.90, stock: 8 },
    ],
    requirements: {
      cpu: 'Intel & AMD',
      windows: '10 - 11',
      cheatType: 'External',
      controller: true,
    },
    createdAt: daysAgo(85),
    updatedAt: daysAgo(3),
  },
  {
    id: 'prod_4',
    name: 'Marvel Rivals',
    slug: 'marvel-rivals',
    description: 'Unleash your powers in Marvel Rivals with our advanced cheat. Perfect aim and complete awareness.',
    image: '/images/marvel-rivals.jpg',
    gallery: ['/images/marvel-rivals.jpg'],
    game: 'Marvel Rivals',
    status: 'active',
    features: {
      aimbot: ['Aimbot enable', 'Auto aim', 'Target lock', 'Ability aim', 'Prediction', 'Priority targeting'],
      esp: ['Enemy ESP', 'Team ESP', 'Health bars', 'Ultimate status', 'Ability cooldowns', '3D boxes'],
      misc: ['No cooldown', 'Auto ultimate', 'Custom crosshair'],
    },
    pricing: [
      { duration: '1 Day', price: 9.90, stock: 25 },
      { duration: '7 Days', price: 49.90, stock: 18 },
      { duration: '30 Days', price: 89.90, stock: 10 },
    ],
    requirements: {
      cpu: 'Intel & AMD',
      windows: '10 - 11',
      cheatType: 'External',
      controller: true,
    },
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_5',
    name: 'Delta Force',
    slug: 'delta-force',
    description: 'Tactical advantage in Delta Force with precision aimbot and comprehensive ESP features.',
    image: '/images/delta-force.jpg',
    gallery: ['/images/delta-force.jpg'],
    game: 'Delta Force',
    status: 'active',
    features: {
      aimbot: ['Aimbot enable', 'Aim key', 'Bone selection', 'Smoothing', 'FOV settings', 'Visibility check'],
      esp: ['Player ESP', 'Box ESP', 'Skeleton', 'Distance', 'Health', 'Weapon info', 'Vehicle ESP'],
      misc: ['No recoil', 'No spread', 'Radar hack', 'Custom crosshair'],
    },
    pricing: [
      { duration: '1 Day', price: 7.90, stock: 20 },
      { duration: '7 Days', price: 39.90, stock: 12 },
      { duration: '30 Days', price: 69.90, stock: 6 },
    ],
    requirements: {
      cpu: 'Intel only',
      windows: '10 - 11',
      cheatType: 'External',
      controller: false,
    },
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: 'prod_6',
    name: 'PUBG',
    slug: 'pubg',
    description: 'Win every chicken dinner with our PUBG cheat. Advanced features for battle royale domination.',
    image: '/images/pubg.jpg',
    gallery: ['/images/pubg.jpg'],
    game: 'PUBG',
    status: 'active',
    features: {
      aimbot: ['Aimbot enable', 'Silent aim', 'Prediction', 'Bone priority', 'Vehicle aim', 'FOV circle'],
      esp: ['Player ESP', 'Vehicle ESP', 'Item ESP', 'Airdrop ESP', 'Distance', 'Health bars', 'Weapon info'],
      misc: ['No recoil', 'No spread', 'Speed hack', 'Car fly', 'Magic bullet'],
    },
    pricing: [
      { duration: '1 Day', price: 6.90, stock: 30 },
      { duration: '7 Days', price: 34.90, stock: 20 },
      { duration: '30 Days', price: 59.90, stock: 10 },
    ],
    requirements: {
      cpu: 'Intel & AMD',
      windows: '10 - 11',
      cheatType: 'External',
      controller: false,
    },
    createdAt: daysAgo(100),
    updatedAt: daysAgo(5),
  },
  {
    id: 'prod_7',
    name: 'DayZ',
    slug: 'dayz',
    description: 'Survive the apocalypse with our DayZ cheat. Find loot, avoid danger, and dominate other survivors.',
    image: '/images/dayz.jpg',
    gallery: ['/images/dayz.jpg'],
    game: 'DayZ',
    status: 'active',
    features: {
      aimbot: ['Aimbot enable', 'Aim key', 'Bone selection', 'Silent aim', 'Prediction'],
      esp: ['Player ESP', 'Zombie ESP', 'Vehicle ESP', 'Item ESP', 'Base ESP', 'Animal ESP', 'Distance'],
      misc: ['No recoil', 'Infinite stamina', 'Night vision', 'Custom crosshair'],
    },
    pricing: [
      { duration: '1 Day', price: 5.90, stock: 25 },
      { duration: '7 Days', price: 29.90, stock: 15 },
      { duration: '30 Days', price: 54.90, stock: 8 },
    ],
    requirements: {
      cpu: 'Intel & AMD',
      windows: '10 - 11',
      cheatType: 'External',
      controller: false,
    },
    createdAt: daysAgo(80),
    updatedAt: daysAgo(4),
  },
  {
    id: 'prod_8',
    name: 'Dune Awakening',
    slug: 'dune-awakening',
    description: 'Conquer Arrakis with our Dune Awakening cheat. Survival advantages in the harsh desert.',
    image: '/images/dune-awakening.jpg',
    gallery: ['/images/dune-awakening.jpg'],
    game: 'Dune Awakening',
    status: 'active',
    features: {
      aimbot: ['Aimbot enable', 'Auto aim', 'Target lock', 'Prediction'],
      esp: ['Player ESP', 'NPC ESP', 'Resource ESP', 'Vehicle ESP', 'Sandworm ESP', 'Base ESP'],
      misc: ['No stamina drain', 'Water hack', 'Resource multiplier', 'Custom crosshair'],
    },
    pricing: [
      { duration: '1 Day', price: 8.90, stock: 20 },
      { duration: '7 Days', price: 44.90, stock: 12 },
      { duration: '30 Days', price: 79.90, stock: 5 },
    ],
    requirements: {
      cpu: 'Intel & AMD',
      windows: '10 - 11',
      cheatType: 'External',
      controller: false,
    },
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_9',
    name: 'Dead by Daylight',
    slug: 'dead-by-daylight',
    description: 'Escape or hunt with ease in Dead by Daylight. Features for both survivors and killers.',
    image: '/images/dead-by-daylight.jpg',
    gallery: ['/images/dead-by-daylight.jpg'],
    game: 'Dead by Daylight',
    status: 'active',
    features: {
      aimbot: ['Auto aim (Killer)', 'Hatchet prediction', 'Blink assist'],
      esp: ['Survivor ESP', 'Killer ESP', 'Generator ESP', 'Totem ESP', 'Hatch ESP', 'Chest ESP', 'Pallet ESP'],
      misc: ['Skill check bot', 'Auto dead hard', 'Speed boost', 'Instant heal'],
    },
    pricing: [
      { duration: '1 Day', price: 5.90, stock: 30 },
      { duration: '7 Days', price: 29.90, stock: 20 },
      { duration: '30 Days', price: 49.90, stock: 12 },
    ],
    requirements: {
      cpu: 'Intel & AMD',
      windows: '10 - 11',
      cheatType: 'External',
      controller: true,
    },
    createdAt: daysAgo(70),
    updatedAt: daysAgo(3),
  },
  {
    id: 'prod_10',
    name: 'ARC Raiders',
    slug: 'arc-raiders',
    description: 'Survive and thrive in ARC Raiders with our premium cheat package.',
    image: '/images/arc-raiders.png',
    gallery: ['/images/arc-raiders.png'],
    game: 'ARC Raiders',
    status: 'active',
    features: {
      aimbot: ['Aimbot enable', 'Auto aim', 'Prediction', 'Bone selection'],
      esp: ['Player ESP', 'Robot ESP', 'Loot ESP', 'Extraction ESP', 'Vehicle ESP'],
      misc: ['No recoil', 'Infinite stamina', 'Custom crosshair'],
    },
    pricing: [
      { duration: '1 Day', price: 7.90, stock: 20 },
      { duration: '7 Days', price: 39.90, stock: 10 },
      { duration: '30 Days', price: 69.90, stock: 5 },
    ],
    requirements: {
      cpu: 'Intel & AMD',
      windows: '10 - 11',
      cheatType: 'External',
      controller: false,
    },
    createdAt: daysAgo(25),
    updatedAt: daysAgo(2),
  },
  {
    id: 'prod_11',
    name: 'Rainbow Six Siege X',
    slug: 'rainbow-six-siege',
    description: 'Tactical supremacy in Rainbow Six Siege with wallhacks, aimbot, and more.',
    image: '/images/rainbow-six.jpg',
    gallery: ['/images/rainbow-six.jpg'],
    game: 'Rainbow Six Siege',
    status: 'active',
    features: {
      aimbot: ['Aimbot enable', 'Triggerbot', 'Silent aim', 'Recoil control', 'FOV settings'],
      esp: ['Player ESP', 'Gadget ESP', 'Camera ESP', 'Bomb ESP', '2D radar', 'Sound ESP'],
      misc: ['No recoil', 'No flash', 'Auto lean', 'Custom crosshair'],
    },
    pricing: [
      { duration: '1 Day', price: 9.90, stock: 15 },
      { duration: '7 Days', price: 49.90, stock: 10 },
      { duration: '30 Days', price: 89.90, stock: 5 },
    ],
    requirements: {
      cpu: 'Intel only',
      windows: '10 - 11',
      cheatType: 'External',
      controller: false,
    },
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },
  {
    id: 'prod_12',
    name: 'Battlefield 6',
    slug: 'battlefield-6',
    description: 'Dominate the battlefield with our advanced Battlefield cheat. All-out warfare advantage.',
    image: '/images/battlefield-6.jpg',
    gallery: ['/images/battlefield-6.jpg'],
    game: 'Battlefield',
    status: 'active',
    features: {
      aimbot: ['Aimbot enable', 'Prediction', 'Vehicle aim', 'Aircraft aim', 'Bone selection'],
      esp: ['Player ESP', 'Vehicle ESP', 'Aircraft ESP', 'Explosive ESP', 'Objective ESP'],
      misc: ['No recoil', 'No spread', 'Instant ADS', 'Radar hack'],
    },
    pricing: [
      { duration: '1 Day', price: 8.90, stock: 20 },
      { duration: '7 Days', price: 44.90, stock: 12 },
      { duration: '30 Days', price: 79.90, stock: 6 },
    ],
    requirements: {
      cpu: 'Intel & AMD',
      windows: '10 - 11',
      cheatType: 'External',
      controller: true,
    },
    createdAt: daysAgo(35),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_13',
    name: 'COD Black Ops 7',
    slug: 'cod-bo7',
    description: 'Latest Call of Duty Black Ops 7 cheat with all premium features. Undetected and updated daily.',
    image: '/images/cod-bo7.jpg',
    gallery: ['/images/cod-bo7.jpg'],
    game: 'Call of Duty: BO7',
    status: 'active',
    features: {
      aimbot: ['Silent aim', 'Bone priority', 'Smoothing', 'FOV circle', 'Prediction', 'Auto fire'],
      esp: ['Box ESP', 'Skeleton', 'Health bars', 'Distance', 'Snaplines', 'Weapon info'],
      misc: ['No recoil', 'No spread', 'Rapid fire', 'UAV always on', 'Unlock all'],
    },
    pricing: [
      { duration: '1 Day', price: 11.90, stock: 25 },
      { duration: '7 Days', price: 54.90, stock: 18 },
      { duration: '30 Days', price: 99.90, stock: 8 },
    ],
    requirements: {
      cpu: 'Intel & AMD',
      windows: '10 - 11',
      cheatType: 'Internal',
      controller: true,
    },
    createdAt: daysAgo(15),
    updatedAt: daysAgo(0),
  },
  {
    id: 'prod_14',
    name: 'COD Black Ops 6',
    slug: 'cod-bo6',
    description: 'Undetected Call of Duty Black Ops 6 cheat with rage and legit modes.',
    image: '/images/cod-bo6.jpg',
    gallery: ['/images/cod-bo6.jpg'],
    game: 'Call of Duty: BO6',
    status: 'active',
    features: {
      aimbot: ['Silent aim', 'Bone prioritization', 'Smoothing', 'FOV circle', 'Prediction'],
      esp: ['Box ESP', 'Skeleton', 'Health bars', 'Distance', 'Snaplines'],
      misc: ['No recoil', 'No spread', 'Rapid fire', 'UAV always on'],
    },
    pricing: [
      { duration: '1 Day', price: 9.90, stock: 20 },
      { duration: '7 Days', price: 49.90, stock: 12 },
      { duration: '30 Days', price: 89.90, stock: 5 },
    ],
    requirements: {
      cpu: 'Intel & AMD',
      windows: '10 - 11',
      cheatType: 'Internal',
      controller: true,
    },
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
  },
  {
    id: 'prod_15',
    name: 'Rust',
    slug: 'rust',
    description: 'Survive and raid with our Rust cheat. Full ESP, aimbot, and utility features.',
    image: '/images/rust.jpg',
    gallery: ['/images/rust.jpg'],
    game: 'Rust',
    status: 'active',
    features: {
      aimbot: ['Aimbot enable', 'Silent aim', 'Bullet prediction', 'Bone selection', 'Recoil control'],
      esp: ['Player ESP', 'Base ESP', 'Stash ESP', 'Animal ESP', 'Ore ESP', 'Hemp ESP', 'Airdrop ESP'],
      misc: ['No recoil', 'Admin flags', 'Auto farm', 'Spider climb', 'Fly hack'],
    },
    pricing: [
      { duration: '1 Day', price: 10.90, stock: 15 },
      { duration: '7 Days', price: 49.90, stock: 10 },
      { duration: '30 Days', price: 89.90, stock: 5 },
    ],
    requirements: {
      cpu: 'Intel & AMD',
      windows: '10 - 11',
      cheatType: 'Internal',
      controller: false,
    },
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
  },
  {
    id: 'prod_16',
    name: 'Escape from Tarkov',
    slug: 'escape-from-tarkov',
    description: 'Survive Tarkov with our premium cheat. Loot ESP, player detection, and extraction help.',
    image: '/images/tarkov.jpg',
    gallery: ['/images/tarkov.jpg'],
    game: 'Escape from Tarkov',
    status: 'active',
    features: {
      aimbot: ['Aimbot enable', 'Silent aim', 'Bone selection', 'Armor penetration calc', 'Prediction'],
      esp: ['Player ESP', 'Scav ESP', 'Boss ESP', 'Loot ESP', 'Container ESP', 'Extract ESP', 'Quest item ESP'],
      misc: ['No recoil', 'No sway', 'Instant ADS', 'Infinite stamina', 'Night vision'],
    },
    pricing: [
      { duration: '1 Day', price: 12.90, stock: 10 },
      { duration: '7 Days', price: 59.90, stock: 8 },
      { duration: '30 Days', price: 109.90, stock: 3 },
    ],
    requirements: {
      cpu: 'Intel only',
      windows: '10 - 11',
      cheatType: 'External',
      controller: false,
    },
    createdAt: daysAgo(75),
    updatedAt: daysAgo(1),
  },
];

// Mock Orders
export const mockOrders: Order[] = [
  {
    id: 'ord_1',
    orderNumber: 'MC-2025-0847',
    customerId: 'cust_1',
    customerEmail: 'player123@gmail.com',
    customerName: 'Player123',
    productId: 'prod_1',
    productName: 'Armani - Apex Legends',
    duration: '7 Days',
    quantity: 1,
    subtotal: 39.90,
    discount: 0,
    total: 39.90,
    status: 'completed',
    paymentMethod: 'stripe',
    paymentId: 'pi_3abc123',
    createdAt: hoursAgo(2),
  },
  {
    id: 'ord_2',
    orderNumber: 'MC-2025-0846',
    customerId: 'cust_2',
    customerEmail: 'gamer_pro@outlook.com',
    customerName: 'GamerPro',
    productId: 'prod_14',
    productName: 'COD Black Ops 6',
    duration: '30 Days',
    quantity: 1,
    subtotal: 89.90,
    discount: 8.99,
    total: 80.91,
    status: 'completed',
    paymentMethod: 'stripe',
    paymentId: 'pi_3def456',
    couponCode: 'SAVE10',
    createdAt: hoursAgo(5),
  },
  {
    id: 'ord_3',
    orderNumber: 'MC-2025-0845',
    customerId: 'cust_3',
    customerEmail: 'newuser@yahoo.com',
    customerName: 'NewUser',
    productId: 'prod_3',
    productName: 'Fortnite',
    duration: '1 Day',
    quantity: 1,
    subtotal: 8.90,
    discount: 0,
    total: 8.90,
    status: 'pending',
    paymentMethod: 'paypal',
    createdAt: hoursAgo(8),
  },
  {
    id: 'ord_4',
    orderNumber: 'MC-2025-0844',
    customerId: 'cust_4',
    customerEmail: 'tarkov_fan@test.com',
    customerName: 'TarkovFan',
    productId: 'prod_16',
    productName: 'Escape from Tarkov',
    duration: '7 Days',
    quantity: 1,
    subtotal: 59.90,
    discount: 0,
    total: 59.90,
    status: 'completed',
    paymentMethod: 'stripe',
    paymentId: 'pi_3ghi789',
    createdAt: daysAgo(1),
  },
  {
    id: 'ord_5',
    orderNumber: 'MC-2025-0843',
    customerId: 'cust_5',
    customerEmail: 'rust_player@example.com',
    customerName: 'RustPlayer',
    productId: 'prod_15',
    productName: 'Rust',
    duration: '30 Days',
    quantity: 1,
    subtotal: 89.90,
    discount: 0,
    total: 89.90,
    status: 'completed',
    paymentMethod: 'crypto',
    createdAt: daysAgo(2),
  },
];

// Mock License Keys
export const mockLicenseKeys: LicenseKey[] = [
  {
    id: 'lic_1',
    key: 'MGMA-APEX-7D8K-X2M4-9PLQ',
    productId: 'prod_1',
    productName: 'Armani - Apex Legends',
    orderId: 'ord_1',
    customerId: 'cust_1',
    customerEmail: 'player123@gmail.com',
    status: 'active',
    duration: '7 Days',
    hwid: 'HW-8A2B-C3D4-E5F6',
    activatedAt: hoursAgo(1),
    expiresAt: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    createdAt: hoursAgo(2),
  },
  {
    id: 'lic_2',
    key: 'MGMA-COD6-30D-Y7N3-4KWR',
    productId: 'prod_14',
    productName: 'COD Black Ops 6',
    orderId: 'ord_2',
    customerId: 'cust_2',
    customerEmail: 'gamer_pro@outlook.com',
    status: 'active',
    duration: '30 Days',
    hwid: 'HW-1X2Y-3Z4A-5B6C',
    activatedAt: hoursAgo(4),
    expiresAt: new Date(Date.now() + 29 * 24 * 60 * 60 * 1000),
    createdAt: hoursAgo(5),
  },
  {
    id: 'lic_3',
    key: 'MGMA-FORT-1D-Q8R2-7TYU',
    productId: 'prod_3',
    productName: 'Fortnite',
    status: 'available',
    duration: '1 Day',
    createdAt: daysAgo(3),
  },
  {
    id: 'lic_4',
    key: 'MGMA-RUST-1D-P5S9-3NMK',
    productId: 'prod_15',
    productName: 'Rust',
    status: 'available',
    duration: '1 Day',
    createdAt: daysAgo(3),
  },
  {
    id: 'lic_5',
    key: 'MGMA-TARK-7D-L4J8-6VBN',
    productId: 'prod_16',
    productName: 'Escape from Tarkov',
    orderId: 'ord_4',
    customerId: 'cust_4',
    customerEmail: 'tarkov_fan@test.com',
    status: 'active',
    duration: '7 Days',
    hwid: 'HW-TRK1-2345-6789',
    activatedAt: daysAgo(1),
    expiresAt: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    createdAt: daysAgo(1),
  },
  {
    id: 'lic_6',
    key: 'MGMA-HWID-LT-Z9X8-C7V6',
    productId: 'prod_2',
    productName: 'HWID Spoofer',
    status: 'available',
    duration: 'Lifetime',
    createdAt: daysAgo(10),
  },
];

// Mock Coupons
export const mockCoupons: Coupon[] = [
  {
    id: 'coup_1',
    code: 'SAVE10',
    type: 'percentage',
    value: 10,
    maxUses: 100,
    usedCount: 47,
    validFrom: daysAgo(30),
    validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    status: 'active',
    createdAt: daysAgo(30),
  },
  {
    id: 'coup_2',
    code: 'WELCOME5',
    type: 'fixed',
    value: 5,
    minPurchase: 20,
    maxUses: 500,
    usedCount: 234,
    validFrom: daysAgo(60),
    validUntil: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    status: 'active',
    createdAt: daysAgo(60),
  },
  {
    id: 'coup_3',
    code: 'APEX20',
    type: 'percentage',
    value: 20,
    maxUses: 50,
    usedCount: 50,
    productIds: ['prod_1'],
    validFrom: daysAgo(14),
    validUntil: daysAgo(1),
    status: 'expired',
    createdAt: daysAgo(14),
  },
  {
    id: 'coup_4',
    code: 'VIP50',
    type: 'percentage',
    value: 50,
    maxUses: 10,
    usedCount: 3,
    validFrom: daysAgo(7),
    validUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    status: 'active',
    createdAt: daysAgo(7),
  },
];

// Mock Webhooks
export const mockWebhooks: Webhook[] = [
  {
    id: 'wh_1',
    name: 'Discord Order Notifications',
    url: 'https://discord.com/api/webhooks/123456789/abcdef',
    events: ['order.completed', 'order.refunded'],
    secret: 'whsec_abc123def456',
    status: 'active',
    lastTriggered: hoursAgo(2),
    failureCount: 0,
    createdAt: daysAgo(30),
  },
  {
    id: 'wh_2',
    name: 'License Activation Logger',
    url: 'https://api.example.com/webhooks/license',
    events: ['license.activated', 'license.expired', 'license.revoked'],
    secret: 'whsec_xyz789ghi012',
    status: 'active',
    lastTriggered: hoursAgo(1),
    failureCount: 0,
    createdAt: daysAgo(20),
  },
  {
    id: 'wh_3',
    name: 'Analytics Endpoint',
    url: 'https://analytics.broken-url.com/hook',
    events: ['order.completed'],
    secret: 'whsec_broken123',
    status: 'inactive',
    lastTriggered: daysAgo(5),
    failureCount: 12,
    createdAt: daysAgo(15),
  },
];

// Mock Team Members
export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm_1',
    userId: 'user_1',
    email: 'admin@magmacheats.com',
    username: 'MagmaAdmin',
    role: 'admin',
    permissions: ['all'],
    avatar: 'MA',
    lastActive: hoursAgo(0),
    invitedBy: 'system',
    joinedAt: daysAgo(365),
  },
  {
    id: 'tm_2',
    userId: 'user_2',
    email: 'mufasa@magmacheats.com',
    username: 'Mufasa',
    role: 'support',
    permissions: ['orders.view', 'orders.refund', 'licenses.view', 'licenses.manage', 'customers.view'],
    avatar: 'MF',
    lastActive: hoursAgo(1),
    invitedBy: 'MagmaAdmin',
    joinedAt: daysAgo(180),
  },
  {
    id: 'tm_3',
    userId: 'user_3',
    email: 'dev@magmacheats.com',
    username: 'DevTeam',
    role: 'admin',
    permissions: ['all'],
    avatar: 'DT',
    lastActive: hoursAgo(3),
    invitedBy: 'MagmaAdmin',
    joinedAt: daysAgo(120),
  },
];

// Mock Activity Logs
export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'log_1',
    userId: 'user_2',
    username: 'Mufasa',
    action: 'order.refund',
    details: 'Refunded order MC-2025-0844 ($49.90)',
    ipAddress: '192.168.1.100',
    timestamp: daysAgo(1),
  },
  {
    id: 'log_2',
    userId: 'user_1',
    username: 'MagmaAdmin',
    action: 'product.update',
    details: 'Updated pricing for Armani - Apex Legends',
    ipAddress: '10.0.0.1',
    timestamp: daysAgo(2),
  },
  {
    id: 'log_3',
    userId: 'user_3',
    username: 'DevTeam',
    action: 'license.generate',
    details: 'Generated 10 license keys for COD Black Ops 6',
    ipAddress: '172.16.0.50',
    timestamp: daysAgo(3),
  },
];

// Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalRevenue: 12847.50,
  revenueChange: 12.5,
  totalOrders: 347,
  ordersChange: 8.3,
  activeUsers: 892,
  usersChange: 15.2,
  activeLicenses: 456,
  licensesChange: -2.4,
};

// Chart Data (last 7 days)
export const mockChartData: ChartData[] = [
  { date: 'Mon', revenue: 1240, orders: 42 },
  { date: 'Tue', revenue: 1890, orders: 58 },
  { date: 'Wed', revenue: 2100, orders: 67 },
  { date: 'Thu', revenue: 1650, orders: 51 },
  { date: 'Fri', revenue: 2450, orders: 78 },
  { date: 'Sat', revenue: 2890, orders: 89 },
  { date: 'Sun', revenue: 2627, orders: 82 },
];

// Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif_1',
    type: 'order',
    title: 'New Order',
    message: 'Order MC-2025-0847 completed ($39.90)',
    read: false,
    createdAt: hoursAgo(2),
  },
  {
    id: 'notif_2',
    type: 'license',
    title: 'License Activated',
    message: 'MGMA-APEX-7D8K-X2M4-9PLQ activated by player123@gmail.com',
    read: false,
    createdAt: hoursAgo(1),
  },
  {
    id: 'notif_3',
    type: 'alert',
    title: 'Low Stock Alert',
    message: 'Tarkov 30-Day keys running low (3 remaining)',
    read: false,
    createdAt: hoursAgo(6),
  },
];
